create table categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    slug varchar(120) not null unique,
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table products (
    id bigint generated by default as identity primary key,
    category_id bigint references categories(id) on delete set null,
    name varchar(200) not null,
    slug varchar(220) not null unique,
    description text,
    price numeric(12, 2) not null,
    condition varchar(30) not null,
    location varchar(150),
    contact_phone varchar(30),
    status varchar(30) not null default 'draft',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id) on delete cascade,
    storage_path text not null,
    image_url text not null,
    display_order integer not null default 0,
    is_primary boolean not null default false,
    created_at timestamptz not null default now()
);

create index idx_products_category_id
on products(category_id);

create index idx_products_status
on products(status);

create index idx_product_images_product_id
on product_images(product_id);

create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists ix_admins_email
on public.admins (email);